####
# See http://www.x.org/archive/X11R7.5/doc/man/man4/synaptics.4.html
###
# synclient LeftEdge=1495
# synclient RightEdge=5447
# synclient TopEdge=1089
# synclient BottomEdge=4763
# When finger pressure drops below this value, the driver counts it as a release. Property: "Synaptics Finger"
# synclient FingerLow=25
# synclient FingerHigh=30
# synclient MaxTapTime=180
# synclient MaxTapMove=276
# synclient MaxDoubleTapTime=100
# synclient SingleTapTimeout=180
# synclient ClickTime=100
# synclient EmulateMidButtonTime=0
# synclient EmulateTwoFingerMinZ=282
# synclient EmulateTwoFingerMinW=7
synclient VertScrollDelta=150
synclient HorizScrollDelta=150
# synclient VertEdgeScroll=1
# synclient HorizEdgeScroll=1
# synclient CornerCoasting=1
synclient VertTwoFingerScroll=1
synclient HorizTwoFingerScroll=1
# synclient MinSpeed=1
# synclient MaxSpeed=1.75
# synclient AccelFactor=0.0318827
# synclient TouchpadOff=0
# synclient LockedDrags=0
# synclient LockedDragTimeout=5000
# synclient RTCornerButton=0
# synclient RBCornerButton=0
# synclient LTCornerButton=0
# synclient LBCornerButton=0
# synclient TapButton1=0
# synclient TapButton2=0
# synclient TapButton3=0
# synclient ClickFinger1=1
# synclient ClickFinger2=3
# synclient ClickFinger3=2
synclient CircularScrolling=1
synclient CircScrollDelta=0.6
synclient CircScrollTrigger=0
# synclient CircularPad=0
# synclient PalmDetect=0
# synclient PalmMinWidth=10
# synclient PalmMinZ=200
synclient CoastingSpeed=20
# synclient CoastingFriction=50
# synclient PressureMotionMinZ=30
# synclient PressureMotionMaxZ=160
# synclient PressureMotionMinFactor=1
# synclient PressureMotionMaxFactor=1
# synclient GrabEventDevice=0
# synclient TapAndDragGesture=1
# synclient AreaLeftEdge=0
# synclient AreaRightEdge=0
# synclient AreaTopEdge=0
# synclient AreaBottomEdge=0
# synclient HorizHysteresis=31
# synclient VertHysteresis=31
# synclient ClickPad=1
# synclient RightButtonAreaLeft=3471
# synclient RightButtonAreaRight=0
# synclient RightButtonAreaTop=4293
# synclient RightButtonAreaBottom=0
# synclient MiddleButtonAreaLeft=0
# synclient MiddleButtonAreaRight=0
# synclient MiddleButtonAreaTop=0
# synclient MiddleButtonAreaBottom=0
