export DOTFILES_OPT_ALL=false
export DOTFILES_OPT_DEBUG=false
export DOTFILES_OPT_RECURSIVE=false
export DOTFILES_OPT_FETCH=false
export DOTFILES_OPT_INTERACTIVE=false
export DOTFILES_OPT_ASSUME_DEFAULT=false
export DOTFILES_OPT_FORCE=false

export DOTFILES_REPODIR="$DOTFILEDIR/repo"
export DOTFILES_REPO_PREFIX="https://github.com/kba/"
export DOTFILES_REPO_SUFFIX=".git"

export DOTFILES_BACKUPDIR="$DOTFILEDIR/.backup"

export DOTFILES_LOCAL_PROFILE="$DOTFILEDIR/profile.local.sh"
